version: "3.8"

services:
    calendar-service:
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        ports:
            - "8008:8008"
        env_file:
            - .env
        environment:
            - REDIS_HOST=redis
            - REDIS_PORT=6379
        volumes:
            - ./src:/app/src
            - ./entrypoint.sh:/app/entrypoint.sh
            - calendar-storage:/app/storage
        depends_on:
            redis:
                condition: service_healthy
        networks:
            - calendar-network
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:8008/health"]
            interval: 30s
            timeout: 10s
            retries: 3
            start_period: 20s

    redis:
        image: redis:7-alpine
        restart: unless-stopped
        command: >
            sh -c 'if [ -n "$REDIS_PASSWORD" ]; then 
                     redis-server --appendonly yes --requirepass "$REDIS_PASSWORD"; 
                   else 
                     redis-server --appendonly yes; 
                   fi'
        volumes:
            - redis-data:/data
        environment:
            - REDIS_PASSWORD=${REDIS_PASSWORD:-}
        networks:
            - calendar-network
        healthcheck:
            test: ["CMD", "sh", "-c", 'if [ -n "$REDIS_PASSWORD" ]; then redis-cli -a "$REDIS_PASSWORD" ping; else redis-cli ping; fi']
            interval: 10s
            timeout: 5s
            retries: 5

networks:
    calendar-network:
        driver: bridge

volumes:
    calendar-storage:
    redis-data:
