version: "3"
services:
    test-calendar-service:
        build: .
        ports:
            - "8008:8008"
        environment:
            - DEBUG=1
            - LOG_LEVEL=DEBUG
        command: python -m uvicorn simplified_main:app --host 0.0.0.0 --port 8008
